#!/bin/bash
#create and a local user config folder and copy all settings to it
#this adds a complete guide to Python Development and GNU Troff please comment out unnecessary lines

cp -r Manuals /home/nigel/
cp -r Pictures /home/nigel/
cp .Xresources /home/nigel/
cp .vimrc /home/nigel
mkdir ~/.config && cp -r .config/* ~/.config/
mkdir ~/Documents

#installing our fave programs
sudo aptitude install pulseaudio pavucontrol screenkey zathura tty-clock xterm htop vim neofetch neomutt isync msmtp pass notmuch mupdf scrot imagemagick polybar font-manager ranger tlp sddm compton python3-pip xorg i3lock feh telegram-desktop firefox-esr ark rofi -y

#make a directory for our sddm user icon and set permissions for sddm replace you
#comment out this line you dont need it unless you want my face on your computer
sudo mkdir -p /usr/share/sddm/faces/ && sudo cp -r ~/debian/nigel.face.icon /usr/share/sddm/faces/
cd ~/Documents/ && git clone https://github.com./K547NK/PythonScripts

#remove those annoying preinstalled tiny text editors which are powerfull yet incomplete
sudo apt remove nano vim-tiny -y


